name: Basic Command

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/2 * * * *"

jobs:
  run-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17




    
  
  
